-- Typed models for the FreeMusic SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class V1List
---@field idAlbum? string
---@field idArtist? string
---@field idIMVDB? string
---@field idLyric? string
---@field idTrack? string
---@field intCD? string
---@field intDuration? string
---@field intLoved? string
---@field intMusicVidComments? string
---@field intMusicVidDislikes? string
---@field intMusicVidFavorites? string
---@field intMusicVidLikes? string
---@field intMusicVidViews? string
---@field intScore? string
---@field intScoreVotes? string
---@field intTotalListeners? string
---@field intTotalPlays? string
---@field intTrackNumber? string
---@field strAlbum? string
---@field strArtist? string
---@field strArtistAlternate? string
---@field strDescriptionEN? string
---@field strGenre? string
---@field strLocked? string
---@field strMood? string
---@field strMusicBrainzAlbumID? string
---@field strMusicBrainzArtistID? string
---@field strMusicBrainzID? string
---@field strMusicVid? string
---@field strMusicVidCompany? string
---@field strMusicVidDirector? string
---@field strMusicVidScreen1? string
---@field strMusicVidScreen2? string
---@field strMusicVidScreen3? string
---@field strStyle? string
---@field strTheme? string
---@field strTrack? string
---@field strTrack3x3? string
---@field strTrackLyrics? string
---@field strTrackThumb? string
---@field trending? table

---@class V1ListLoadMatch
---@field api_key string

---@class V1ListListMatch
---@field api_key string

---@class V1Lookup
---@field idAlbum? string
---@field idArtist? string
---@field idIMVDB? string
---@field idLabel? string
---@field idLyric? string
---@field idTrack? string
---@field intBornYear? string
---@field intCD? string
---@field intCharted? string
---@field intDiedYear? string
---@field intDuration? string
---@field intFormedYear? string
---@field intLoved? string
---@field intMembers? string
---@field intMusicVidComments? string
---@field intMusicVidDislikes? string
---@field intMusicVidFavorites? string
---@field intMusicVidLikes? string
---@field intMusicVidViews? string
---@field intSales? string
---@field intScore? string
---@field intScoreVotes? string
---@field intTotalListeners? string
---@field intTotalPlays? string
---@field intTrackNumber? string
---@field intYearReleased? string
---@field strAlbum? string
---@field strAlbum3DCase? string
---@field strAlbum3DFace? string
---@field strAlbum3DFlat? string
---@field strAlbum3DThumb? string
---@field strAlbumCDart? string
---@field strAlbumSpine? string
---@field strAlbumStripped? string
---@field strAlbumThumb? string
---@field strAlbumThumbBack? string
---@field strAlbumThumbHQ? string
---@field strAllMusicID? string
---@field strAmazonID? string
---@field strArtist? string
---@field strArtistAlternate? string
---@field strArtistBanner? string
---@field strArtistClearart? string
---@field strArtistCutout? string
---@field strArtistFanart? string
---@field strArtistFanart2? string
---@field strArtistFanart3? string
---@field strArtistFanart4? string
---@field strArtistLogo? string
---@field strArtistStripped? string
---@field strArtistThumb? string
---@field strArtistWideThumb? string
---@field strBBCReviewID? string
---@field strBiographyEN? string
---@field strCountry? string
---@field strCountryCode? string
---@field strDescriptionEN? string
---@field strDisbanded? string
---@field strDiscogsID? string
---@field strFacebook? string
---@field strGender? string
---@field strGeniusID? string
---@field strGenre? string
---@field strISNIcode? string
---@field strItunesID? string
---@field strLabel? string
---@field strLastFMChart? string
---@field strLocation? string
---@field strLocked? string
---@field strLyricWikiID? string
---@field strMood? string
---@field strMusicBrainzAlbumID? string
---@field strMusicBrainzArtistID? string
---@field strMusicBrainzID? string
---@field strMusicMozID? string
---@field strMusicVid? string
---@field strMusicVidCompany? string
---@field strMusicVidDirector? string
---@field strMusicVidScreen1? string
---@field strMusicVidScreen2? string
---@field strMusicVidScreen3? string
---@field strRateYourMusicID? string
---@field strReleaseFormat? string
---@field strReview? string
---@field strSpeed? string
---@field strStyle? string
---@field strTheme? string
---@field strTrack? string
---@field strTrack3x3? string
---@field strTrackLyrics? string
---@field strTrackThumb? string
---@field strTwitter? string
---@field strWebsite? string
---@field strWikidataID? string
---@field strWikipediaID? string

---@class V1LookupLoadMatch
---@field api_key string

---@class V1LookupListMatch
---@field api_key string

---@class V1Search
---@field album? table
---@field idAlbum? string
---@field idArtist? string
---@field idIMVDB? string
---@field idLabel? string
---@field idLyric? string
---@field idTrack? string
---@field intBornYear? string
---@field intCD? string
---@field intCharted? string
---@field intDiedYear? string
---@field intDuration? string
---@field intFormedYear? string
---@field intLoved? string
---@field intMembers? string
---@field intMusicVidComments? string
---@field intMusicVidDislikes? string
---@field intMusicVidFavorites? string
---@field intMusicVidLikes? string
---@field intMusicVidViews? string
---@field intSales? string
---@field intScore? string
---@field intScoreVotes? string
---@field intTotalListeners? string
---@field intTotalPlays? string
---@field intTrackNumber? string
---@field intYearReleased? string
---@field strAlbum? string
---@field strAlbum3DCase? string
---@field strAlbum3DFace? string
---@field strAlbum3DFlat? string
---@field strAlbum3DThumb? string
---@field strAlbumCDart? string
---@field strAlbumSpine? string
---@field strAlbumStripped? string
---@field strAlbumThumb? string
---@field strAlbumThumbBack? string
---@field strAlbumThumbHQ? string
---@field strAllMusicID? string
---@field strAmazonID? string
---@field strArtist? string
---@field strArtistAlternate? string
---@field strArtistBanner? string
---@field strArtistClearart? string
---@field strArtistCutout? string
---@field strArtistFanart? string
---@field strArtistFanart2? string
---@field strArtistFanart3? string
---@field strArtistFanart4? string
---@field strArtistLogo? string
---@field strArtistStripped? string
---@field strArtistThumb? string
---@field strArtistWideThumb? string
---@field strBBCReviewID? string
---@field strBiographyEN? string
---@field strCountry? string
---@field strCountryCode? string
---@field strDescriptionEN? string
---@field strDisbanded? string
---@field strDiscogsID? string
---@field strFacebook? string
---@field strGender? string
---@field strGeniusID? string
---@field strGenre? string
---@field strISNIcode? string
---@field strItunesID? string
---@field strLabel? string
---@field strLastFMChart? string
---@field strLocation? string
---@field strLocked? string
---@field strLyricWikiID? string
---@field strMood? string
---@field strMusicBrainzAlbumID? string
---@field strMusicBrainzArtistID? string
---@field strMusicBrainzID? string
---@field strMusicMozID? string
---@field strMusicVid? string
---@field strMusicVidCompany? string
---@field strMusicVidDirector? string
---@field strMusicVidScreen1? string
---@field strMusicVidScreen2? string
---@field strMusicVidScreen3? string
---@field strRateYourMusicID? string
---@field strReleaseFormat? string
---@field strReview? string
---@field strSpeed? string
---@field strStyle? string
---@field strTheme? string
---@field strTrack? string
---@field strTrack3x3? string
---@field strTrackLyrics? string
---@field strTrackThumb? string
---@field strTwitter? string
---@field strWebsite? string
---@field strWikidataID? string
---@field strWikipediaID? string

---@class V1SearchLoadMatch
---@field api_key string

---@class V1SearchListMatch
---@field api_key string

---@class V2List
---@field album? table

---@class V2ListLoadMatch
---@field id_artist number

---@class V2Lookup
---@field album? table
---@field artists? table
---@field track? table

---@class V2LookupLoadMatch
---@field id_album number

---@class V2Search
---@field album? table
---@field artists? table
---@field track? table

---@class V2SearchLoadMatch
---@field album_name string

local M = {}

return M
